### PR TITLE
Fix source URL in rockspec

### PR DESCRIPTION
**Pull request by ciarand**
v1.1.0 not v1.1.1 (this patch attempts to fixes the following error):

```
Error: Failed installing dependency: http://rocks.moonscript.org/mediator_lua-1.1.1-0.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/mediator_lua/archive/v1.1.1.tar.gz
```

### CODE REVIEW

**Comment by amireh** [comment]
+1, can't currently install busted with luarocks.

**Comment by thibaultCha** [comment]
iirc, you also need to rename `mediator_lua-1.1.1-0.rockspec` to `mediator_lua-1.1.1-1.rockspec` to allow   the maintainers to publish a new version on luarocks.

**Comment by thibaultCha** [comment]
Although I believe the real fix would be to create a `1.1.1` tag, as it seems to be the desired version.

**Comment by ciarand** [comment]
Yeah, tbh I'm happy however it gets fixed

**Comment by o-lim** [comment]
Looks like this PR is no longer necessary, as the mediator version tag has been fixed.

**Pull request closed without merging**
